export type Project = {
  id: number;
  slug: string;
  title: string;
  description: string;
  longDescription?: string;
  reflections?: string;
  image: string;
  github: string;
  demo?: string;
  tags: string[];
  date: string;
};

export const projects: Project[] = [
  {
    id: 1,
    slug: 'multicalc',
    title: 'MultiCalc - Calculator',
    description: 'MultiCalc is a simple, fast, and user-friendly online calculator that makes everyday arithmetic easy and accessible for everyone.',
    longDescription: 'MultiCalc was designed to provide a lightweight, lightning-fast alternative to complex calculation tools. By stripping away unnecessary features and focusing on core arithmetic needs, the application delivers instant results without overwhelming the user. It is fully responsive, ensuring a seamless experience across desktop and mobile devices.',
    reflections: 'This project reinforced the importance of simplicity in product design—removing unnecessary complexity often creates more value than adding features.',
    image: '/project/multicalc1.png',
    github: 'https://github.com/codewithdhruba01/MultiCalc',
    demo: 'https://www.multicalc.site/',
    tags: ['React', 'TypeScript', 'Node.js', 'Full Stack', 'MDX', 'Motion', 'Vercel'],
    date: 'Aug 2026',
  },
  {
    id: 2,
    slug: 'github-developer-tools',
    title: 'GitHub Developer Tools',
    description: 'Advanced GitHub tools for developers follower analytics, README designer, comparison, and documentation.',
    longDescription: 'GitHub Developer Tools provides an all-in-one suite for developers to enhance their GitHub profiles and analyze their open-source presence. Features include an interactive README designer, detailed follower analytics, and repository comparison tools, built to empower developers to present their work effectively.',
    reflections: 'Building tools for developers requires a deep understanding of their workflows. Creating intuitive interfaces for complex data visualization was a key learning experience.',
    image: '/project/GithubDevloperTools-cover.png',
    github: 'https://github.com/codewithdhruba01/GithubProtools',
    demo: 'https://githubprotools.vercel.app/',
    tags: ['React', 'Next.js', 'REST API', 'TypeScript', 'Frontend', 'Shadcn', 'Vercel', 'Node.js'],
    date: 'Jul 2026',
  },
  {
    id: 3,
    slug: 'outfit-wallpaper-generator',
    title: 'Outfit Wallpaper Generator',
    description: 'Outfit Wallpaper Generator is a sleek and interactive tool for creating personalized phone wallpapers in your preferred colors, offering both gradient and solid options.',
    longDescription: 'This application allows users to craft completely personalized aesthetic wallpapers for their mobile devices. With an intuitive color picker and gradient builder, users can experiment with different combinations and instantly download high-quality wallpapers.',
    reflections: 'Working with canvas APIs and image generation directly in the browser taught me how to optimize client-side performance while delivering high-quality visual outputs.',
    image: '/project/wallpaperapp.png',
    github: 'https://github.com/codewithdhruba01/OutfitWallpaper',
    demo: 'https://outfitwallpaper.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'TypeScript', 'Node.js', 'Vercel', 'Frontend'],
    date: 'Jun 2026',
  },
  {
    id: 4,
    slug: 'dictionary-webapp',
    title: 'Dictionary - WebApp',
    description: 'A beautifully designed dictionary web app that allows you to look up any English word and explore rich details such as meanings, pronunciations, usage examples, synonyms, and much more.',
    longDescription: 'The Dictionary WebApp leverages external public APIs to provide comprehensive linguistic data instantly. It features a clean, distraction-free interface that presents definitions, phonetics, and synonyms in an easily digestible format.',
    reflections: 'Handling complex API responses and elegantly parsing nested data structures was crucial for this project. It emphasized the need for robust error handling and loading states.',
    image: '/project/Dictionary-cover.png',
    github: 'https://github.com/codewithdhruba01/Dictionary_Website',
    demo: 'https://dictionary-website-silk.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'TypeScript', 'Node.js', 'Vercel', 'Motion', 'Frontend'],
    date: 'May 2026',
  },
  {
    id: 5,
    slug: 'typing-master',
    title: 'Typing Master',
    description: 'A modern, feature-rich typing test application. Test your typing speed and accuracy with customizable settings, real-time statistics, and professional-grade performance tracking.',
    longDescription: 'Typing Master is designed to help users improve their keyboard skills through interactive and customizable tests. The app provides real-time feedback on WPM, accuracy, and keystroke metrics, wrapping it all in a sleek, animated UI.',
    reflections: 'Implementing precise timing and real-time state updates without performance lag was a significant technical challenge that improved my React state management skills.',
    image: '/project/typingmaster-cover.png',
    github: 'https://github.com/codewithdhruba01/TypeMaster',
    demo: 'https://type-master-iota-three.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'TypeScript', 'Motion', 'Node.js', 'Vercel', 'Frontend'],
    date: 'Apr 2026',
  },
  {
    id: 6,
    slug: 'ip-address-tracker',
    title: 'IP Address Tracker',
    description: 'A beautiful, modern web application for tracking and locating IP addresses in real-time with an interactive map interface.',
    longDescription: 'This application integrates IP geolocation APIs with interactive mapping libraries to provide precise geographical context for any given IP address or domain. It features a responsive layout and smooth transitions.',
    reflections: 'Integrating multiple third-party services (APIs and Maps) required careful orchestration of asynchronous operations and solid state architecture.',
    image: '/project/IPAddressTracker.png',
    github: 'https://github.com/codewithdhruba01/IP-AddressTracker',
    demo: 'https://ip-tracker-cyan-nu.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'TypeScript', 'Node.js', 'Vercel', 'Frontend'],
    date: 'Mar 2026',
  },
  {
    id: 7,
    slug: 'colorkit-webapp',
    title: 'ColorKit WebApp',
    description: 'A professional, feature-rich color picker and analysis tool Extract colors from images, generate color palettes, analyze accessibility, and explore color theory with an elegant, animated interface.',
    longDescription: 'ColorKit is a comprehensive suite of tools for designers and developers. It provides color extraction from images, automated palette generation, and accessibility contrast checking, all wrapped in a visually stunning interface.',
    reflections: 'Building tools that operate primarily on visual logic required a deep dive into color theory algorithms, color space conversions, and interactive UI design.',
    image: '/project/colorkit.png',
    github: 'https://github.com/codewithdhruba01/ColorPicker',
    demo: 'https://colorskit.vercel.app/',
    tags: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Motion', 'Shadcn', 'Vercel', 'Node.js'],
    date: 'Feb 2026',
  },
  {
    id: 8,
    slug: 'emojihub-webapp',
    title: 'EmojiHub WebApp',
    description: 'A beautiful and fully functional emoji search-and-copy application featuring smooth animations, intuitive interactions, and a modern, polished interface.',
    longDescription: 'EmojiHub provides a blazing-fast search experience over a massive dataset of emojis. Users can easily find, copy, and explore emojis categorized logically, enhanced by smooth micro-interactions.',
    reflections: 'Optimizing search and rendering performance for large datasets was a primary focus. I learned to leverage virtualization and debouncing to maintain a smooth user experience.',
    image: '/project/emojihub-cover.png',
    github: 'https://github.com/codewithdhruba01/EmojiHub',
    demo: 'https://emojihub.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'TypeScript', 'Motion', 'Node.js', 'Vercel', 'Frontend'],
    date: 'Jan 2026',
  },
  {
    id: 9,
    slug: 'flipclock',
    title: 'FlipClock - Aesthetic Clock',
    description: 'A modern, minimal digital clock with an elegant flip animation and a clutter-free interface designed to enhance focus, relaxation, and mindfulness.',
    longDescription: 'FlipClock serves as an ambient, focus-enhancing utility. By emulating the aesthetic of retro flip clocks with modern CSS animations, it provides a visually pleasing way to keep time without distractions.',
    reflections: 'Achieving a realistic, smooth 3D flip animation entirely with CSS transforms and transitions was a highly rewarding exercise in advanced CSS.',
    image: '/project/flipclock-cover.png',
    github: 'https://github.com/codewithdhruba01/FlipClock',
    demo: 'https://flip-clocks.vercel.app/',
    tags: ['Next.js', 'Tailwind CSS', 'TypeScript', 'REST API', 'Motion', 'Shadcn', 'Node.js', 'Vercel', 'Frontend'],
    date: 'Dec 2025',
  },
  {
    id: 10,
    slug: 'college-fee-payment',
    title: 'College Fee Payment Portal',
    description: 'A simple and responsive College Fee Payment Portal built using HTML, CSS, and JavaScript.',
    longDescription: 'This project is a conceptual frontend implementation of a secure payment portal for educational institutions. It focuses on form validation, clear user flows, and responsive design.',
    reflections: 'Working with pure HTML, CSS, and JavaScript without frameworks reinforced my fundamental web development skills and understanding of the DOM.',
    image: '/project/collegepayment.png',
    github: 'https://github.com/codewithdhruba01/fPortalcollege',
    demo: 'https://codewithdhruba01.github.io/fPortalcollege/',
    tags: ['Html', 'CSS', 'JavaScript', 'Frontend'],
    date: 'Nov 2025',
  },
  {
    id: 11,
    slug: 'face-recognition-realtime',
    title: 'Face Recognition Real-Time',
    description: 'Real-time Face Attendance System using OpenCV for recognition.',
    longDescription: 'This application utilizes computer vision techniques to identify individuals in real-time video streams. It was designed as a prototype for automated attendance systems in educational or corporate environments.',
    reflections: 'Diving into Python and OpenCV was a fascinating shift from web development. It highlighted the challenges of real-time processing and the intricacies of machine learning models.',
    image: '/project/facesystem.jpg',
    github: 'https://github.com/codewithdhruba01/FaceRecognitionRealTime',
    tags: ['Python', 'OpenCV', 'cvzone', 'NumPy', 'AI/ML', 'ML'],
    date: 'Oct 2025',
  },
  {
    id: 12,
    slug: 'comfortpg-website',
    title: 'ComfortPG-Website',
    description: 'A modern, responsive Paying Guest accommodation website',
    longDescription: 'ComfortPG is a platform designed to simplify the process of finding and booking paying guest accommodations. It features property listings, detailed amenity views, and a responsive layout for mobile users.',
    reflections: 'Designing a platform that caters to both property owners and seekers required careful consideration of user journeys and information architecture.',
    image: '/project/comfortpg.png',
    github: 'https://github.com/codewithdhruba01/ComfortPG_Website',
    demo: 'https://comfort-pg.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'Node.js', 'Motion', 'Frontend', 'TypeScript', 'Vercel'],
    date: 'Sep 2025',
  },
];
