export type Project = {
  id: number;
  slug: string;
  title: string;
  description: string;
  longDescription?: string;
  reflections?: string;
  image: string;
  github: string;
  demo?: string;
  tags: string[];
  date: string;
  features?: { title: string; description: string }[];
  featuresHtml?: string;
  reflectionsHtml?: string;
};

export const projects: Project[] = [
  {
    id: 1,
    slug: 'xmedia',
    title: 'XMedia',
    description: 'X Media Downloader is a modern web app that lets users download videos from public X posts by simply pasting a post URL.',
    longDescription: 'X-Media Downloader is a premium, full-stack, glassmorphic web application built with <strong class="text-white font-semibold">React, Express, and TypeScript</strong> that extracts direct, downloadable MP4 video stream URLs from public Twitter/X posts.<br/><br/>This project does not use the official Twitter API. Instead, it leverages a reverse-engineered token calculation and queries the public Twitter Syndication API, replicating the behavior of official embedded web widgets.',
    reflections: 'Developing an efficient backend for media extraction while maintaining a clean, user-friendly frontend taught me a lot about API integrations and full-stack performance optimization.',
    image: '/project/xmedia.png',
    github: 'https://github.com/codewithdhruba01/X-Downloader',
    demo: 'https://xmedia-one.vercel.app/',
    tags: ['TypeScript', 'Express.js', 'Tailwind CSS', 'Node.js', 'Full Stack'],
    date: 'Jul 2025',
    features: [
      { title: 'High-End Design System', description: 'Modern Glassmorphic UI with dynamic animated gradients, customizable dark/light themes, and custom animations utilizing Framer Motion.' },
      { title: 'Micro-Animations', description: 'Smooth scale changes, sliding cards, and audio-style loading equalizers.' },
      { title: 'Multiple Video Resolutions', description: 'Extracts and displays all available MP4 resolutions (e.g., 1080p, 720p, 480p, 360p) sorted by quality.' },
      { title: 'Interactive Video Preview', description: 'Directly preview the video in a premium player before downloading.' },
      { title: 'Download History', description: "Stores past downloads in the browser's LocalStorage with quick-reload, individual deletion, and history wipe controls." },
      { title: 'Quick-Copy Stream Links', description: 'Direct buttons to copy raw CDN links or copy the post URL.' },
      { title: 'Advanced Backend Protections', description: 'Integrates helmet security headers, custom logging, and rate limiting (max 30 download requests/15 mins per IP).' },
      { title: 'TypeScript Everywhere', description: 'Strong types on both frontend and backend for robust, type-safe execution.' }
    ]
  },
  {
    id: 2,
    slug: 'colorkit-webapp',
    title: 'ColorKit',
    description: 'A professional, feature-rich color picker and analysis tool Extract colors from images, generate color palettes, analyze accessibility.',
    longDescription: 'ColorKit is a premium, all-in-one color management platform designed to elevate your creative workflow. Whether you\'re extracting the perfect shade from an image, generating harmonious palettes, or ensuring your designs meet global accessibility standards, ColorKit provides a seamless, highly visual experience.<br/><br/>Built for designers, developers, and creative minds, it allows you to explore the depths of color theory, test real-time contrast, and manage your color assets with an elegant, animated interface that inspires creativity at every click.',
    reflections: 'Building tools that operate primarily on visual logic required a deep dive into color theory algorithms, color space conversions, and interactive UI design.',
    reflectionsHtml: '<p class="mb-4">Analyzing <strong class="text-white font-medium">ColorKit</strong> reveals a meticulously crafted application that stands out for several reasons:</p><ol class="list-decimal list-outside ml-5 space-y-3 mb-6"><li><strong class="text-white font-medium">Focus on Accessibility</strong>: Beyond just picking colors, the inclusion of a robust Contrast Checker and Color Blindness Simulator demonstrates a deep understanding of modern web development standards. It encourages designers to create inclusive digital experiences.</li><li><strong class="text-white font-medium">Exceptional User Experience</strong>: The integration of <code class="bg-neutral-800 text-neutral-300 px-1.5 py-0.5 rounded text-sm font-mono">framer-motion</code> for micro-interactions and <code class="bg-neutral-800 text-neutral-300 px-1.5 py-0.5 rounded text-sm font-mono">lenis</code> for smooth scrolling creates a highly polished, "premium" feel. The glassmorphism UI and animated gradient backgrounds make the app visually stunning without compromising performance.</li><li><strong class="text-white font-medium">Solid Technical Foundation</strong>: Utilizing Next.js App Router along with TypeScript and Zustand ensures that the application is scalable, maintainable, and type-safe. The modular component structure (<code class="bg-neutral-800 text-neutral-300 px-1.5 py-0.5 rounded text-sm font-mono">components/color-picker</code>, <code class="bg-neutral-800 text-neutral-300 px-1.5 py-0.5 rounded text-sm font-mono">components/home</code>, etc.) reflects excellent separation of concerns.</li><li><strong class="text-white font-medium">Comprehensive Tooling</strong>: Integrating advanced algorithms like K-means clustering for image color extraction directly in the browser using the HTML5 Canvas API showcases a high level of technical competency.</li><li><strong class="text-white font-medium">Modern Authentication & Data</strong>: The groundwork laid with <code class="bg-neutral-800 text-neutral-300 px-1.5 py-0.5 rounded text-sm font-mono">Clerk</code> and <code class="bg-neutral-800 text-neutral-300 px-1.5 py-0.5 rounded text-sm font-mono">Supabase</code> indicates that the app is built to be a fully-fledged SaaS product, capable of saving user preferences, palettes, and historical data.</li></ol><p>ColorKit is not just a utility; it is a comprehensive suite for color management that perfectly balances aesthetic appeal with technical depth.</p>',
    featuresHtml: '<h3 class="text-xl font-bold text-white mb-4">Advanced Color Picking Tools</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Image Color Extraction</strong>: Upload images and instantly extract dominant color palettes using a k-means clustering algorithm.</li><li><strong class="text-white font-medium">Click-to-Pick</strong>: Interactively click anywhere on an uploaded image to pick precise pixel colors.</li><li><strong class="text-white font-medium">Manual Color Picker</strong>: Highly interactive visual color picker with RGB and HSL sliders.</li><li><strong class="text-white font-medium">Native Color Input</strong>: Quick access to the browser\'s native color picker.</li><li><strong class="text-white font-medium">Instant Color Picker Component</strong>: Pick colors directly from the homepage seamlessly.</li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4">Comprehensive Color Formats & Conversions</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Technical Formats</strong>: Live conversion between <strong class="text-white font-medium">HEX, RGB, HSL, HSV, and CMYK</strong>.</li><li><strong class="text-white font-medium">Practical Formats</strong>: Support for CSS RGB/HSL, Android Color Format, Swift UIColor.</li><li><strong class="text-white font-medium">Easy Export</strong>: One-click copy-to-clipboard functionality for all formats.</li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4">Accessibility & Contrast Checker</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">WCAG Compliance</strong>: Built-in checker for WCAG AA (4.5:1) and AAA (7:1) contrast standards.</li><li><strong class="text-white font-medium">Real-time Preview</strong>: Test text legibility on colored backgrounds.</li><li><strong class="text-white font-medium">Smart Recommendations</strong>: Pass/fail feedback and actionable accessibility insights.</li><li><strong class="text-white font-medium">Color Blindness Simulator</strong>: Simulate how colors appear to people with Protanopia, Deuteranopia, and Tritanopia.</li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4">Color Theory & Palettes</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Harmonious Combinations</strong>: Generate Complementary, Analogous, Triadic, and Tetradic schemes.</li><li><strong class="text-white font-medium">Color Variations</strong>: Easily generate shades (adding black), tints (adding white), and tones (adding gray).</li><li><strong class="text-white font-medium">Curated Palettes & Gradients</strong>: Explore and manage beautiful pre-designed color palettes and gradients.</li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4">Color Analysis</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li>Color name identification based on hex codes.</li><li>Breakdown of Hue, Saturation, Lightness, and Brightness.</li><li>Temperature analysis (warm/cool) and vibrancy levels.</li><li>Mood associations and best use-case recommendations.</li></ul>',
    image: '/project/colorkit.png',
    github: 'https://github.com/codewithdhruba01/ColorPicker',
    demo: 'https://colorskit.vercel.app/',
    tags: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Figma', 'Motion', 'Shadcn', 'Vercel'],
    date: 'Jul 2026',
  },
  {
    id: 3,
    slug: 'multicalc',
    title: 'MultiCalc - Calculator',
    description: 'MultiCalc is a simple, fast, and user-friendly online calculator that makes everyday arithmetic easy and accessible for everyone.',
    longDescription: 'MultiCalc is a lightweight, responsive, and intuitive web-based calculator built to simplify everyday arithmetic operations. Designed with simplicity and usability in mind, it provides a clean interface that allows users of all backgrounds to perform basic mathematical calculations effortlessly. Whether you\'re a student needing quick calculations, a professional who wants a handy digital calculator, or just someone who prefers an elegant web app over traditional calculators, MultiCalc is the perfect solution.',
    reflections: 'This project reinforced the importance of simplicity in product design—removing unnecessary complexity often creates more value than adding features.',
    featuresHtml: '<ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-3 mb-12"><li><strong class="text-white font-medium">Instant Calculation</strong>: See results in real time as you enter your numbers.</li><li><strong class="text-white font-medium">Cross-Platform</strong>: Works seamlessly on desktops, tablets, and smartphones.</li><li><strong class="text-white font-medium">Fast & Lightweight</strong>: No heavy dependencies; loads instantly.</li><li><strong class="text-white font-medium">Minimalistic UI</strong>: Focuses on clarity and ease of use without any clutter.</li><li><strong class="text-white font-medium">Easy to Customize</strong>: Simple code structure makes it easy for developers to extend functionality.</li></ul><h2 class="text-2xl md:text-3xl font-bold font-bricolage text-neutral-200 mb-6 border-b border-neutral-800/50 pb-3 mt-12">Available Calculators</h2><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-12 grid grid-cols-1 sm:grid-cols-2 gap-y-2 gap-x-8"><li><strong class="text-white font-medium">Basic Calculator</strong></li><li><strong class="text-white font-medium">Scientific Calculator</strong></li><li><strong class="text-white font-medium">BMI Calculator</strong></li><li><strong class="text-white font-medium">BMR Calculator</strong></li><li><strong class="text-white font-medium">Protein Calculator</strong></li><li><strong class="text-white font-medium">Pregnancy Calculator</strong></li><li><strong class="text-white font-medium">Age Calculator</strong></li><li><strong class="text-white font-medium">Period Calculator</strong></li><li><strong class="text-white font-medium">Percentage Calculator</strong></li><li><strong class="text-white font-medium">Loan Calculator</strong></li><li><strong class="text-white font-medium">ROI Calculator</strong></li><li><strong class="text-white font-medium">NPV Calculator</strong></li><li><strong class="text-white font-medium">Unit Converter</strong></li><li><strong class="text-white font-medium">Price to Weight Converter</strong></li><li><strong class="text-white font-medium">Salary Calculator</strong></li><li><strong class="text-white font-medium">Currency Calculator</strong></li></ul>',
    image: '/project/multicalc1.png',
    github: 'https://github.com/codewithdhruba01/MultiCalc',
    demo: 'https://www.multicalc.site/',
    tags: ['React', 'TypeScript', 'Node.js', 'Full Stack', 'MDX', 'Motion', 'Vercel'],
    date: 'Jun 2025',
  },
  {
    id: 4,
    slug: 'github-developer-tools',
    title: 'GitHub Developer Tools',
    description: 'Advanced GitHub tools for developers follower analytics, README designer, comparison, and documentation.',
    longDescription: 'GitHub Developer Tools provides an all-in-one suite for developers to enhance their GitHub profiles and analyze their open-source presence. Features include an interactive README designer, detailed follower analytics, and repository comparison tools, built to empower developers to present their work effectively.',
    reflections: 'Building tools for developers requires a deep understanding of their workflows. Creating intuitive interfaces for complex data visualization was a key learning experience.',
    featuresHtml: '<h3 class="text-xl font-bold text-white mb-4">GitHub Analytics</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Follower Counter</strong>: Real-time GitHub follower tracking with detailed insights</li><li><strong class="text-white font-medium">Following Analysis</strong>: Discover who you\'re following that doesn\'t follow back</li><li><strong class="text-white font-medium">Profile Comparison</strong>: Compare GitHub profiles side-by-side with improvement suggestions</li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4">Profile Tools</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">README Designer</strong>: Create stunning GitHub profile READMEs with:<ul class="list-[circle] list-outside ml-5 mt-2 space-y-1"><li>Skills icons and technology badges</li><li>Social media links and contact information</li><li>GitHub statistics and contribution widgets</li><li>Live preview and downloadable markdown files</li></ul></li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4">Learning Resources</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Comprehensive Documentation</strong>: Complete Git and GitHub learning resources</li><li><strong class="text-white font-medium">Chapter-wise Organization</strong>: From basics to advanced techniques</li><li><strong class="text-white font-medium">Interactive Examples</strong>: Practical code examples and commands</li><li><strong class="text-white font-medium">FAQ Section</strong>: Answers to common questions</li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4 font-hanken">Tech Stack</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Next.js 13</strong>: React framework with App Router</li><li><strong class="text-white font-medium">TypeScript</strong>: Type-safe development</li><li><strong class="text-white font-medium">Tailwind CSS</strong>: Utility-first CSS framework</li><li><strong class="text-white font-medium">shadcn/ui</strong>: Modern component library</li><li><strong class="text-white font-medium">Framer Motion</strong>: Smooth animations and transitions</li><li><strong class="text-white font-medium">GitHub API</strong>: Real-time data fetching</li><li><strong class="text-white font-medium">Vercel</strong>: Deployment and hosting</li><li><strong class="text-white font-medium">Static Export</strong>: Optimized for performance</li><li><strong class="text-white font-medium">ESLint</strong>: Code linting and quality</li><li><strong class="text-white font-medium">Prettier</strong>: Code formatting</li><li><strong class="text-white font-medium">Git</strong>: Version control</li><li><strong class="text-white font-medium">VS Code</strong>: Recommended development environment</li></ul>',
    image: '/project/GithubDevloperTools-cover.png',
    github: 'https://github.com/codewithdhruba01/GithubProtools',
    demo: 'https://githubprotools.vercel.app/',
    tags: ['React', 'Next.js', 'REST API', 'TypeScript', 'Frontend', 'Shadcn', 'Vercel', 'Node.js'],
    date: 'Aug 2025',
  },
  {
    id: 5,
    slug: 'outfit-wallpaper-generator',
    title: 'Outfit Wallpaper Generator',
    description: 'Outfit Wallpaper Generator is a sleek and interactive tool for creating personalized phone wallpapers in your preferred colors',
    longDescription: 'Outfit Wallpaper Generator is a modern, interactive web application that allows users to create personalized phone wallpapers based on their color preferences. The app provides a seamless, intuitive interface for generating unique wallpapers with gradient and solid color options.',
    reflections: 'Working with canvas APIs and image generation directly in the browser taught me how to optimize client-side performance while delivering high-quality visual outputs.',
    featuresHtml: '<ul class="list-none list-outside text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-3 mb-12"><li class="flex items-center gap-3"><span class="text-xl"></span> <strong class="text-white font-medium">Color-based Wallpaper Generation</strong></li><li class="flex items-center gap-3"><span class="text-xl"></span> <strong class="text-white font-medium">Gradient and Solid Color Options</strong></li><li class="flex items-center gap-3"><span class="text-xl"></span> <strong class="text-white font-medium">Mobile-Friendly Design</strong></li><li class="flex items-center gap-3"><span class="text-xl"></span> <strong class="text-white font-medium">Dark/Light Theme Support</strong></li><li class="flex items-center gap-3"><span class="text-xl"></span> <strong class="text-white font-medium">Instant Wallpaper Download</strong></li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4 flex items-center gap-2"><span class="text-xl"></span> Tech Stack</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Frontend</strong>: React (TypeScript)</li><li><strong class="text-white font-medium">Styling</strong>: Tailwind CSS</li><li><strong class="text-white font-medium">Build Tool</strong>: Vite</li><li><strong class="text-white font-medium">State Management</strong>: React Context</li><li><strong class="text-white font-medium">Color Manipulation</strong>: TinyColor</li></ul>',
    image: '/project/wallpaperapp.png',
    github: 'https://github.com/codewithdhruba01/OutfitWallpaper',
    demo: 'https://outfitwallpaper.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'TypeScript', 'Node.js', 'Vercel', 'Frontend'],
    date: 'Jun 2025',
  },
  {
    id: 6,
    slug: 'dictionary-webapp',
    title: 'Dictionary - WebApp',
    description: 'A beautifully designed dictionary web app that allows you to look up any English word and explore rich details such as meanings, pronunciations, usage examples, synonyms, and much more.',
    longDescription: '<p class="mb-8">The Dictionary WebApp leverages external public APIs to provide comprehensive linguistic data instantly. It features a clean, distraction-free interface that presents definitions, phonetics, and synonyms in an easily digestible format.</p><h3 class="text-xl font-bold text-white mb-4">Searching for Words</h3><ol class="list-decimal list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li>Type any English word in the search bar</li><li>Results appear automatically after 500ms of inactivity</li><li>View complete word information including multiple meanings</li></ol><h3 class="text-xl font-bold text-white mt-8 mb-4">Changing Fonts</h3><ol class="list-decimal list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li>Click the "Font Selector" dropdown in the navbar</li><li>Choose from Sans Serif, Serif, or Mono</li><li>The entire app font changes instantly</li><li>Your selection is saved automatically</li></ol><h3 class="text-xl font-bold text-white mt-8 mb-4">Listening to Pronunciation</h3><ol class="list-decimal list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li>Search for a word that has audio pronunciation</li><li>Click the purple play button next to the word</li><li>The pronunciation audio plays automatically</li></ol>',
    reflections: 'Handling complex API responses and elegantly parsing nested data structures was crucial for this project. It emphasized the need for robust error handling and loading states.',
    featuresHtml: '<h3 class="text-xl font-bold text-white mb-4">Core Dictionary Functionality</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Real-time Word Search</strong>: Type to search for any English word from the Dictionary API</li><li><strong class="text-white font-medium">Complete Word Information</strong>: Display word, phonetics, pronunciation audio, meanings, definitions, examples, and synonyms</li><li><strong class="text-white font-medium">Multiple Word Forms</strong>: Support for different parts of speech (noun, verb, adjective, etc.)</li><li><strong class="text-white font-medium">Source Links</strong>: Direct links to authoritative sources for each word</li><li><strong class="text-white font-medium">Audio Pronunciation</strong>: Play pronunciation audio for words when available</li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4">User Experience</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Smart Search</strong>: 500ms debounce to avoid excessive API calls while typing</li><li><strong class="text-white font-medium">Loading States</strong>: Beautiful animated spinner during API requests</li><li><strong class="text-white font-medium">Error Handling</strong>: User-friendly messages for "word not found" and network errors</li><li><strong class="text-white font-medium">Smooth Animations</strong>: Framer Motion animations for all transitions and interactions</li><li><strong class="text-white font-medium">Responsive Design</strong>: Fully responsive UI that works perfectly on mobile, tablet, and desktop</li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4">Tech Stack</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Framework</strong>: Next.js 14 (App Router)</li><li><strong class="text-white font-medium">Language</strong>: TypeScript</li><li><strong class="text-white font-medium">Styling</strong>: Tailwind CSS</li><li><strong class="text-white font-medium">UI Components</strong>: shadcn/ui</li><li><strong class="text-white font-medium">Animations</strong>: Framer Motion</li><li><strong class="text-white font-medium">Icons</strong>: Lucide React</li><li><strong class="text-white font-medium">API</strong>: Dictionary API (api.dictionaryapi.dev)</li><li><strong class="text-white font-medium">State Management</strong>: React Hooks (useState, useContext)</li></ul>',
    image: '/project/Dictionary-cover.png',
    github: 'https://github.com/codewithdhruba01/Dictionary_Website',
    demo: 'https://dictionary-website-silk.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'TypeScript', 'Node.js', 'Vercel', 'Motion', 'Frontend'],
    date: 'Nov 2025',
  },
  {
    id: 7,
    slug: 'typing-master',
    title: 'Typing Master',
    description: 'A modern, feature-rich typing test application. Test your typing speed and accuracy with customizable settings, real-time statistics, and professional-grade performance tracking.',
    longDescription: '<strong class="text-white font-semibold">TypeMaster</strong> is a modern, feature-rich typing test application designed to help you improve your typing speed and accuracy. Test your skills with customizable settings, track your performance with real-time statistics, and get classified into professional-grade skill levels. Whether you are a beginner learning to type or an expert aiming to break records, TypeMaster provides a clean, distraction-free environment to practice and grow.',
    reflections: 'Implementing precise timing and real-time state updates without performance lag was a significant technical challenge that improved my React state management skills.',
    featuresHtml: '<ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">Flexible Test Modes</strong>: Choose between Time-based tests (30s, 1m, 2m, 5m) or Word-based tests (25, 50, 100, 200 words) to suit your practice routine.</li><li><strong class="text-white font-medium">Adjustable Difficulty</strong>: Select from Easy, Medium, or Hard text complexities to continually challenge yourself.</li><li><strong class="text-white font-medium">Real-Time Analytics</strong>: Instantly track your Net WPM (Words Per Minute), Gross WPM, and Accuracy percentage as you type.</li><li><strong class="text-white font-medium">Visual Character Feedback</strong>: Get immediate color-coded visual cues (green for correct, red for incorrect, blue for current) to easily spot mistakes.</li><li><strong class="text-white font-medium">Pause & Resume Functionality</strong>: Need a break? Pause your active test at any time and resume exactly where you left off.</li><li><strong class="text-white font-medium">Performance Classification</strong>: Automatically get graded into skill brackets (Novice, Beginner, Intermediate, Advanced, Expert) based on your final WPM.</li><li><strong class="text-white font-medium">Modern & Responsive UI</strong>: A beautifully crafted, smooth, and distraction-free interface that works seamlessly across desktop, tablet, and mobile devices.</li></ul><h3 class="text-xl font-bold text-white mt-8 mb-4">Tech Stack</h3><ul class="list-disc list-outside ml-5 text-[#909092] leading-relaxed text-[1rem] font-hanken space-y-2 mb-6"><li><strong class="text-white font-medium">React</strong>: Core library for building the highly interactive user interface.</li><li><strong class="text-white font-medium">TypeScript</strong>: Ensures robust code architecture and type safety across the application.</li><li><strong class="text-white font-medium">Vite</strong>: Next-generation frontend tooling for lightning-fast development and optimized production builds.</li><li><strong class="text-white font-medium">Tailwind CSS</strong>: Utility-first CSS framework for crafting a modern, responsive, and custom design system.</li><li><strong class="text-white font-medium">Lucide React</strong>: Provides beautiful, consistent, and customizable SVG icons used throughout the app.</li><li><strong class="text-white font-medium">ESLint</strong>: Enforces code quality, consistency, and best practices.</li><li><strong class="text-white font-medium">PostCSS & Autoprefixer</strong>: Used for processing modern CSS and ensuring cross-browser compatibility.</li></ul>',
    image: '/project/typingmaster-cover.png',
    github: 'https://github.com/codewithdhruba01/TypeMaster',
    demo: 'https://type-master-iota-three.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'TypeScript', 'Motion', 'Node.js', 'Vercel', 'Frontend'],
    date: 'Nov 2025',
  },
  {
    id: 8,
    slug: 'ip-address-tracker',
    title: 'IP Address Tracker',
    description: 'A beautiful, modern web application for tracking and locating IP addresses in real-time with an interactive map interface.',
    longDescription: 'This application integrates IP geolocation APIs with interactive mapping libraries to provide precise geographical context for any given IP address or domain. It features a responsive layout and smooth transitions.',
    reflections: 'Integrating multiple third-party services (APIs and Maps) required careful orchestration of asynchronous operations and solid state architecture.',
    image: '/project/IPAddressTracker.png',
    github: 'https://github.com/codewithdhruba01/IP-AddressTracker',
    demo: 'https://ip-tracker-cyan-nu.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'TypeScript', 'Node.js', 'Vercel', 'Frontend'],
    date: 'Mar 2026',
  },
  {
    id: 9,
    slug: 'emojihub-webapp',
    title: 'EmojiHub WebApp',
    description: 'A beautiful and fully functional emoji search-and-copy application featuring smooth animations, intuitive interactions, and a modern, polished interface.',
    longDescription: 'EmojiHub provides a blazing-fast search experience over a massive dataset of emojis. Users can easily find, copy, and explore emojis categorized logically, enhanced by smooth micro-interactions.',
    reflections: 'Optimizing search and rendering performance for large datasets was a primary focus. I learned to leverage virtualization and debouncing to maintain a smooth user experience.',
    image: '/project/emojihub-cover.png',
    github: 'https://github.com/codewithdhruba01/EmojiHub',
    demo: 'https://emojihub.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'TypeScript', 'Motion', 'Node.js', 'Vercel', 'Frontend'],
    date: 'Nov 2025',
  },
  {
    id: 10,
    slug: 'flipclock',
    title: 'FlipClock - Aesthetic Clock',
    description: 'A modern, minimal digital clock with an elegant flip animation and a clutter-free interface designed to enhance focus, relaxation, and mindfulness.',
    longDescription: 'FlipClock serves as an ambient, focus-enhancing utility. By emulating the aesthetic of retro flip clocks with modern CSS animations, it provides a visually pleasing way to keep time without distractions.',
    reflections: 'Achieving a realistic, smooth 3D flip animation entirely with CSS transforms and transitions was a highly rewarding exercise in advanced CSS.',
    image: '/project/flipclock-cover.png',
    github: 'https://github.com/codewithdhruba01/FlipClock',
    demo: 'https://flip-clocks.vercel.app/',
    tags: ['Next.js', 'Tailwind CSS', 'TypeScript', 'REST API', 'Motion', 'Shadcn', 'Node.js', 'Vercel', 'Frontend'],
    date: 'Dec 2025',
  },
  {
    id: 11,
    slug: 'college-fee-payment',
    title: 'College Fee Payment Portal',
    description: 'A simple and responsive College Fee Payment Portal built using HTML, CSS, and JavaScript.',
    longDescription: 'This project is a conceptual frontend implementation of a secure payment portal for educational institutions. It focuses on form validation, clear user flows, and responsive design.',
    reflections: 'Working with pure HTML, CSS, and JavaScript without frameworks reinforced my fundamental web development skills and understanding of the DOM.',
    image: '/project/collegepayment.png',
    github: 'https://github.com/codewithdhruba01/fPortalcollege',
    demo: 'https://codewithdhruba01.github.io/fPortalcollege/',
    tags: ['Html', 'CSS', 'JavaScript', 'Frontend'],
    date: 'Nov 2025',
  },
  {
    id: 12,
    slug: 'face-recognition-realtime',
    title: 'Face Recognition Real-Time',
    description: 'Real-time Face Attendance System using OpenCV for recognition.',
    longDescription: 'This application utilizes computer vision techniques to identify individuals in real-time video streams. It was designed as a prototype for automated attendance systems in educational or corporate environments.',
    reflections: 'Diving into Python and OpenCV was a fascinating shift from web development. It highlighted the challenges of real-time processing and the intricacies of machine learning models.',
    image: '/project/facesystem.jpg',
    github: 'https://github.com/codewithdhruba01/FaceRecognitionRealTime',
    tags: ['Python', 'OpenCV', 'cvzone', 'NumPy', 'AI/ML', 'ML'],
    date: 'Oct 2025',
  },
  {
    id: 13,
    slug: 'comfortpg-website',
    title: 'ComfortPG-Website',
    description: 'A modern, responsive Paying Guest accommodation website',
    longDescription: 'ComfortPG is a platform designed to simplify the process of finding and booking paying guest accommodations. It features property listings, detailed amenity views, and a responsive layout for mobile users.',
    reflections: 'Designing a platform that caters to both property owners and seekers required careful consideration of user journeys and information architecture.',
    image: '/project/comfortpg.png',
    github: 'https://github.com/codewithdhruba01/ComfortPG_Website',
    demo: 'https://comfort-pg.vercel.app/',
    tags: ['React', 'Tailwind CSS', 'Node.js', 'Motion', 'Frontend', 'TypeScript', 'Vercel'],
    date: 'Sep 2025',
  },
];
